# hello_world_with_gem.rb

# Require the faker gem
require 'faker'

# Check if GEM_HOME is set and print its value
gem_home = ENV['GEM_HOME']
if gem_home.nil?
  puts "GEM_HOME is not set."
else
  puts "GEM_HOME is set to: #{gem_home}"
end

# Print "Hello, World!" along with a random name generated by the faker gem
puts "Hello, #{Faker::Name.name}!"
